# Generated by Django 2.2.7 on 2020-02-23 08:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('student_class', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField(null=True)),
                ('acadamic_year', models.PositiveIntegerField(null=True)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('qualifications', models.CharField(max_length=255)),
                ('subject_teaches', models.CharField(max_length=10)),
                ('contact_num', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentParentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('postal_code', models.CharField(max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.StudentInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telugu', models.FloatField(validators=[django.core.validators.MinValueValidator(28.0), django.core.validators.MaxValueValidator(100.0)])),
                ('hindi', models.FloatField(validators=[django.core.validators.MinValueValidator(28.0), django.core.validators.MaxValueValidator(100.0)])),
                ('english', models.FloatField(validators=[django.core.validators.MinValueValidator(28.0), django.core.validators.MaxValueValidator(100.0)])),
                ('maths', models.FloatField(validators=[django.core.validators.MinValueValidator(28.0), django.core.validators.MaxValueValidator(100.0)])),
                ('science', models.FloatField(validators=[django.core.validators.MinValueValidator(28.0), django.core.validators.MaxValueValidator(100.0)])),
                ('social', models.FloatField(validators=[django.core.validators.MinValueValidator(28.0), django.core.validators.MaxValueValidator(100.0)])),
                ('total_marks', models.IntegerField()),
                ('student', models.ForeignKey(on_delete='do_nothing', to='admission.StudentInfo')),
            ],
        ),
    ]
