# Generated by Django 2.2.7 on 2020-02-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='english',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='results',
            name='hindi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='results',
            name='maths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='results',
            name='science',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='results',
            name='social',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='results',
            name='telugu',
            field=models.IntegerField(default=0),
        ),
    ]
