# Generated by Django 2.2.7 on 2020-02-25 06:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_remove_results_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 2, 25, 6, 54, 43, 414842, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
