# Generated by Django 2.2.7 on 2020-02-25 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_auto_20200225_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='student_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='student_profile_image'),
            preserve_default=False,
        ),
    ]
