# Generated by Django 2.2.7 on 2020-02-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_remove_results_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='semester',
            field=models.CharField(blank=True, choices=[('quarterly', 'Quarterly Exam'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly')], max_length=100),
        ),
    ]
